In [1]:
import os
from collections import Counter

In [2]:
folder='email/'

In [3]:
files=os.listdir(folder)

In [4]:
len(files)

5172

In [5]:
emails=[folder + file for file in files]
emails

['email/0001.1999-12-10.farmer.ham.txt',
 'email/0002.1999-12-13.farmer.ham.txt',
 'email/0003.1999-12-14.farmer.ham.txt',
 'email/0004.1999-12-14.farmer.ham.txt',
 'email/0005.1999-12-14.farmer.ham.txt',
 'email/0006.2003-12-18.GP.spam.txt',
 'email/0007.1999-12-14.farmer.ham.txt',
 'email/0008.2003-12-18.GP.spam.txt',
 'email/0009.1999-12-14.farmer.ham.txt',
 'email/0010.1999-12-14.farmer.ham.txt',
 'email/0011.1999-12-14.farmer.ham.txt',
 'email/0012.1999-12-14.farmer.ham.txt',
 'email/0013.1999-12-14.farmer.ham.txt',
 'email/0014.1999-12-15.farmer.ham.txt',
 'email/0015.1999-12-15.farmer.ham.txt',
 'email/0016.1999-12-15.farmer.ham.txt',
 'email/0017.2003-12-18.GP.spam.txt',
 'email/0018.2003-12-18.GP.spam.txt',
 'email/0019.1999-12-15.farmer.ham.txt',
 'email/0020.1999-12-15.farmer.ham.txt',
 'email/0021.1999-12-15.farmer.ham.txt',
 'email/0022.1999-12-16.farmer.ham.txt',
 'email/0023.1999-12-16.farmer.ham.txt',
 'email/0024.1999-12-16.farmer.ham.txt',
 'email/0025.1999-12-16.farm

In [6]:
words=[]
for email in emails:
    f=open(email,encoding='latin-1')
    blob=f.read()
    words+=blob.split(" ")

In [7]:
len(words)

1083821

In [8]:
words[0:5]

['Subject:', 'christmas', 'tree', 'farm', 'pictures\n']

In [9]:
for i in range(len(words)):
    if not words[i].isalpha():
        words[i]=""

In [10]:
word_dictionary=Counter(words)
del word_dictionary[""]
word_dictionary=word_dictionary.most_common(10000)

In [15]:
word_dictionary[9:11]

[('in', 6885), ('on', 6723)]

In [88]:
len(word_dictionary)

10000

In [89]:
feature_set=[]
labels=[]
for email in emails:
    f=open(email,encoding='latin-1')
    blob=f.read().split(" ")
    data=[]
    for i in word_dictionary:
        data.append(blob.count(i[0]))
    
    feature_set.append(data)
    if 'ham' in email:
        labels.append(0)
    if 'spam' in email:
        labels.append(1)

In [90]:
len(feature_set)

5172

In [92]:
import numpy as np
feature_set=np.array(feature_set)
labels=np.array(labels)

In [93]:
feature_set.shape
labels.shape

(5172,)

In [94]:
feature_set

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 5,  4, 12, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 2,  7,  0, ...,  0,  0,  0],
       [19, 18,  0, ...,  0,  0,  0]])

In [105]:
from sklearn.cross_validation import train_test_split

X_train,X_test,y_train,y_test=train_test_split(feature_set,labels,test_size=0.2,random_state=20)

In [106]:
from sklearn.naive_bayes import MultinomialNB
clf=MultinomialNB()
clf.fit(X_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [107]:
y_pred=clf.predict(X_test)

In [108]:
y_test[562]
clf.predict(X_test[562].reshape(1,-1))

array([1])

In [109]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.970048309178744

In [110]:
email_text="""Hi lucky Winner
you are the winner of the contest.you win money,discout is the"""

In [111]:
word=email_text.split(" ")
word

['Hi',
 'lucky',
 'Winner\nyou',
 'are',
 'the',
 'winner',
 'of',
 'the',
 'contest.you',
 'win',
 'money,discout',
 'is',
 'the']

In [112]:
new_word=[]
for i in word_dictionary:
    new_word.append(word.count(i[0]))

In [113]:
new_word=np.array(new_word)

In [116]:
new_word.reshape(10000,1)

array([[3],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [117]:
clf.predict(new_word.reshape(1,-1))

array([1])