In [1]:
l=list(range(1000))

In [2]:
l

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [3]:
import numpy as np

In [4]:
arr=np.arange(10)

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
list1=[[1,2,3],[4,5,6]]

In [4]:
list1

[[1, 2, 3], [4, 5, 6]]

In [14]:
list1[1][2]=99

In [32]:
list1

NameError: name 'Info' is not defined

In [34]:
for i in list1:
    for j in i:
        print(j)

1
2
3
4
5
99


In [35]:
import numpy as np

In [37]:
arr1=np.array([[1,2,3],[4,5,6]])

In [38]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
type(arr1)

numpy.ndarray

In [40]:
arr1.shape

(2, 3)

In [41]:
arr1[1]

array([4, 5, 6])

In [44]:
for i in arr1:
    for j in i:
        print(j)

1
2
3
4
5
6


In [45]:
arr1[1][1]=77

In [46]:
arr1


array([[ 1,  2,  3],
       [ 4, 77,  6]])

In [50]:
arr1=arr1.reshape(3,2)

In [55]:
arr1


array([[ 1,  2],
       [ 3,  4],
       [77,  6]])

In [62]:
arr1.itemsize

4

In [65]:
arr1.itemset(1,8)

In [66]:
arr1

array([[ 1,  8],
       [ 3,  4],
       [77,  6]])

In [68]:
arr1.resize(2,3)

In [69]:
arr1

array([[ 1,  8,  3],
       [ 4, 77,  6]])

In [70]:
arr1+2

array([[ 3, 10,  5],
       [ 6, 79,  8]])

In [73]:
arr1.astype('float')

array([[ 1.,  8.,  3.],
       [ 4., 77.,  6.]])

In [75]:
arr1[:1]

array([[1, 8, 3]])

In [80]:
arr1

array([[ 1,  8,  3],
       [ 4, 77,  6]])

In [76]:
arr1.transpose()

array([[ 1,  4],
       [ 8, 77],
       [ 3,  6]])

In [83]:
arr1.sum(axis=1)

array([12, 87])

In [85]:
import pandas as pd
import numpy as np

In [86]:
df=pd.read_csv('matches.csv')

In [90]:
df

id  season           city        date                        team1  \
0      1    2017      Hyderabad  2017-04-05          Sunrisers Hyderabad   
1      2    2017           Pune  2017-04-06               Mumbai Indians   
2      3    2017         Rajkot  2017-04-07                Gujarat Lions   
3      4    2017         Indore  2017-04-08       Rising Pune Supergiant   
4      5    2017      Bangalore  2017-04-08  Royal Challengers Bangalore   
5      6    2017      Hyderabad  2017-04-09                Gujarat Lions   
6      7    2017         Mumbai  2017-04-09        Kolkata Knight Riders   
7      8    2017         Indore  2017-04-10  Royal Challengers Bangalore   
8      9    2017           Pune  2017-04-11             Delhi Daredevils   
9     10    2017         Mumbai  2017-04-12          Sunrisers Hyderabad   
10    11    2017        Kolkata  2017-04-13              Kings XI Punjab   
11    12    2017      Bangalore  2017-04-14  Royal Challengers Bangalore   
12    13    2017         Rajkot  2017-04-14       Rising Pune Supergiant   
13    14    2017        Kolkata  2017-04-15        Kolkata Knight Riders   
14    15    2017          Delhi  2017-04-15             Delhi Daredevils   
15    16    2017         Mumbai  2017-04-16                Gujarat Lions   
16    17    2017      Bangalore  2017-04-16       Rising Pune Supergiant   
17    18    2017          Delhi  2017-04-17             Delhi Daredevils   
18    19    2017      Hyderabad  2017-04-17          Sunrisers Hyderabad   
19    20    2017         Rajkot  2017-04-18  Royal Challengers Bangalore   
20    21    2017      Hyderabad  2017-04-19          Sunrisers Hyderabad   
21    22    2017         Indore  2017-04-20              Kings XI Punjab   
22    23    2017        Kolkata  2017-04-21        Kolkata Knight Riders   
23    24    2017         Mumbai  2017-04-22               Mumbai Indians   
24    25    2017           Pune  2017-04-22          Sunrisers Hyderabad   
25    26    2017         Rajkot  2017-04-23              Kings XI Punjab   
26    27    2017        Kolkata  2017-04-23        Kolkata Knight Riders   
27    28    2017         Mumbai  2017-04-24       Rising Pune Supergiant   
28    29    2017           Pune  2017-04-26       Rising Pune Supergiant   
29    30    2017      Bangalore  2017-04-27  Royal Challengers Bangalore   
..   ...     ...            ...         ...                          ...   
606  607    2016         Rajkot  2016-05-03                Gujarat Lions   
607  608    2016        Kolkata  2016-05-04        Kolkata Knight Riders   
608  609    2016          Delhi  2016-05-05             Delhi Daredevils   
609  610    2016      Hyderabad  2016-05-06                Gujarat Lions   
610  611    2016      Bangalore  2016-05-07      Rising Pune Supergiants   
611  612    2016     Chandigarh  2016-05-07              Kings XI Punjab   
612  613    2016  Visakhapatnam  2016-05-08          Sunrisers Hyderabad   
613  614    2016        Kolkata  2016-05-08        Kolkata Knight Riders   
614  615    2016     Chandigarh  2016-05-09  Royal Challengers Bangalore   
615  616    2016  Visakhapatnam  2016-05-10          Sunrisers Hyderabad   
616  617    2016      Bangalore  2016-05-11  Royal Challengers Bangalore   
617  618    2016      Hyderabad  2016-05-12          Sunrisers Hyderabad   
618  619    2016  Visakhapatnam  2016-05-13               Mumbai Indians   
619  620    2016      Bangalore  2016-05-14  Royal Challengers Bangalore   
620  621    2016        Kolkata  2016-05-14      Rising Pune Supergiants   
621  622    2016     Chandigarh  2016-05-15              Kings XI Punjab   
622  623    2016  Visakhapatnam  2016-05-15               Mumbai Indians   
623  624    2016        Kolkata  2016-05-16        Kolkata Knight Riders   
624  625    2016  Visakhapatnam  2016-05-17             Delhi Daredevils   
625  626    2016      Bangalore  2016-05-18  Royal Challengers Bangalore   
626  627    2016         Kanpur  2016-05-19        Kol

In [95]:
df[:4][:3]

id  season       city        date                team1  \
0   1    2017  Hyderabad  2017-04-05  Sunrisers Hyderabad   
1   2    2017       Pune  2017-04-06       Mumbai Indians   
2   3    2017     Rajkot  2017-04-07        Gujarat Lions   

                         team2                  toss_winner toss_decision  \
0  Royal Challengers Bangalore  Royal Challengers Bangalore         field   
1       Rising Pune Supergiant       Rising Pune Supergiant         field   
2        Kolkata Knight Riders        Kolkata Knight Riders         field   

   result  dl_applied                  winner  win_by_runs  win_by_wickets  \
0  normal           0     Sunrisers Hyderabad           35               0   
1  normal           0  Rising Pune Supergiant            0               7   
2  normal           0   Kolkata Knight Riders            0              10   

  player_of_match                                      venue         umpire1  \
0    Yuvraj Singh  Rajiv Gandhi International Stadium, Uppal     AY Dandekar   
1       SPD Smith    Maharashtra Cricket Association Stadium  A Nand Kishore   
2         CA Lynn     Saurashtra Cricket Association Stadium     Nitin Menon   

     umpire2  umpire3  
0   NJ Llong      NaN  
1     S Ravi      NaN  
2  CK Nandan      NaN

In [96]:
df[:4][['city','winner']]

city                  winner
0  Hyderabad     Sunrisers Hyderabad
1       Pune  Rising Pune Supergiant
2     Rajkot   Kolkata Knight Riders
3     Indore         Kings XI Punjab

In [1]:
f=(lambda x,y:x+y)

In [2]:
f(3,4)

7

In [3]:
list1=[1,2,3,4,5]

In [43]:
list(filter(lambda x:x%2==0,list1))

[2, 4]

[<function __main__.<lambda>(x)>, [1, 2, 3, 4, 5]]

In [41]:
list(map(lambda x : x*2, [1, 2, 3, 4]))

[2, 4, 6, 8]

In [1]:
import numpy as np
import pandas as pd

In [2]:
delivery=pd.read_csv('deliveries.csv')

In [4]:
delivery.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150460 entries, 0 to 150459
Data columns (total 21 columns):
match_id            150460 non-null int64
inning              150460 non-null int64
batting_team        150460 non-null object
bowling_team        150460 non-null object
over                150460 non-null int64
ball                150460 non-null int64
batsman             150460 non-null object
non_striker         150460 non-null object
bowler              150460 non-null object
is_super_over       150460 non-null int64
wide_runs           150460 non-null int64
bye_runs            150460 non-null int64
legbye_runs         150460 non-null int64
noball_runs         150460 non-null int64
penalty_runs        150460 non-null int64
batsman_runs        150460 non-null int64
extra_runs          150460 non-null int64
total_runs          150460 non-null int64
player_dismissed    7438 non-null object
dismissal_kind      7438 non-null object
fielder             5369 non-null object
dtype

In [20]:
delivery['batsman'].reset_index().iloc[12]

index                12
batsman    MC Henriques
Name: 12, dtype: object

In [1]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
tips=sns.load_dataset('tips')

In [3]:
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4